=== api-evangelist/oracle/json-schema/oci-compute-instance-shape-config-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "InstanceShapeConfig",
  "type": "object",
  "description": "The shape configuration for an instance. This includes the number of OCPUs, amount of memory, and networking bandwidth.",
  "properties": {
    "ocpus": {
      "type": "number",
      "description": "The total number of OCPUs available to the instance"
    },
    "memoryInGBs": {
      "type": "number",
      "description": "The total amount of memory available to the instance, in gigabytes"
    },
    "baselineOcpuUtilization": {
      "type": "string",
      "description": "The baseline OCPU utilization for a subcore burstable instance"
    },
    "processorDescription": {
      "type": "string",
      "description": "A short description of the instance processor"
    },
    "networkingBandwidthInGbps": {
      "type": "number",
      "description": "The networking bandwidth available to the instance, in Gbps"
    },
    "maxVnicAttachments": {
      "type": "integer",
      "description": "The maximum number of VNIC attachments for the instance"
    },
    "gpus": {
      "type": "integer",
      "description": "The number of GPUs available to the instance"
    },
    "gpuDescription": {
      "type": "string",
      "description": "A short description of the instance GPU"
    },
    "localDisks": {
      "type": "integer",
      "description": "The number of local disks available to the instance"
    },
    "localDisksTotalSizeInGBs": {
      "type": "number",
      "description": "The aggregate size of all local disks, in gigabytes"
    },
    "vcpus": {
      "type": "integer",
      "description": "The total number of VCPUs available to the instance. This is typically 2x the number of OCPUs."
    }
  }
}

=== api-evangelist/oracle/examples/oci-compute-instance-shape-config-example.json
{
  "ocpus": 42.5,
  "memoryInGBs": 42.5,
  "baselineOcpuUtilization": "example_value",
  "processorDescription": "example_value",
  "networkingBandwidthInGbps": 42.5,
  "maxVnicAttachments": 10,
  "gpus": 10,
  "gpuDescription": "example_value",
  "localDisks": 10,
  "localDisksTotalSizeInGBs": 42.5,
  "vcpus": 10
}
